### ISSUE TITLE
Integrate the unsubscribe flow in the front-end

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#216] opened 2019-02-07 07:20 UTC
DoD:
- [ ] the user profile menu has a link to a user profile page
- [ ] the user profile page presents an unsubscribe button
- [ ] when the user click this button the system will ask for confirmation
- [ ] after confirmation the user is logged out and removed from the cognito user pool

**Comment by maxvisser** [comment] 2019-02-26 08:18
duplicate of #112

**Closed by maxvisser** 2019-02-26 08:18 UTC
